# Generated by Django 2.2.10 on 2021-01-14 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='sub',
            new_name='topic',
        ),
    ]
