# Generated by Django 3.1.2 on 2020-12-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='camera',
        ),
        migrations.AddField(
            model_name='room',
            name='camera',
            field=models.ManyToManyField(blank=True, to='camera.Camera'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='device',
        ),
        migrations.AddField(
            model_name='room',
            name='device',
            field=models.ManyToManyField(blank=True, to='camera.Device'),
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='room',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='room',
            field=models.ManyToManyField(to='camera.Room'),
        ),
    ]
