# Generated by Django 2.2.10 on 2021-01-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_auto_20210115_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='warning',
            field=models.CharField(blank=True, choices=[('IMD', 'Camera Secure system 1'), ('DRN', 'Camera Secure system 2'), ('NULL', "Don't use security feature")], default='NULL', max_length=2),
        ),
    ]
