# Generated by Django 3.1.2 on 2020-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cam_url',
            field=models.CharField(default='url', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
