# Generated by Django 2.2.10 on 2021-01-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_camera_warning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='warning',
        ),
        migrations.AddField(
            model_name='camera',
            name='warning_system',
            field=models.CharField(choices=[('NULL', "Don't use warning system"), ('IMD', 'Camera warning system 1'), ('DRN', 'Camera warning system 2')], default='NULL', max_length=2),
        ),
    ]
