# Generated by Django 3.1.2 on 2020-12-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_auto_20201205_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='camera.room'),
            preserve_default=False,
        ),
    ]
