# Generated by Django 2.2.10 on 2021-01-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_auto_20210125_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='warning_system',
            field=models.CharField(choices=[(0, "Don't use warning system"), (1, 'Camera warning system 1'), (2, 'Camera warning system 2')], default='NULL', max_length=100),
        ),
    ]
