# Generated by Django 2.2.10 on 2021-01-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0009_auto_20210125_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='cv',
            field=models.BooleanField(default=True),
        ),
    ]
