# Generated by Django 2.2.10 on 2021-01-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0010_camera_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cam_url',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='warning_system',
            field=models.CharField(choices=[('0', "Don't use warning system"), ('1', 'Warning system 1'), ('2', 'Warning system 2')], default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='topic',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
