# Generated by Django 3.1.5 on 2021-01-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0011_auto_20210127_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
