# Generated by Django 3.1.5 on 2021-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0012_auto_20210127_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qos',
            field=models.CharField(blank=True, choices=[('0', 'QoS 0'), ('1', 'QoS 1'), ('2', 'QoS 2')], default='0', max_length=5),
        ),
    ]
