# Generated by Django 3.1.5 on 2021-01-29 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0013_device_qos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='cv',
            new_name='ai_enable',
        ),
    ]
