# Generated by Django 3.1.5 on 2021-01-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0014_auto_20210129_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='qos',
            field=models.CharField(choices=[('0', 'QoS 0'), ('1', 'QoS 1'), ('2', 'QoS 2')], default='0', max_length=5),
        ),
    ]
